import { ConversionTrackerData } from "./types";

export const mockConversionTrackerReports: ConversionTrackerData[] = [
{
  "id": "conversion-tracker-0914-0920",
  "metadata": {
    "reportType": "CDR Conversion Tracker",
    "cadence": "Weekly",
    "periodLabel": "09/14 \u2013 09/20"
  },
  "methodology": {
    "sfThreshold": 33.1,
    "campThreshold": 11.4,
    "sfThresholdBasis": "Average Qualified PCs among CDRs with Short Funnel activity this week (zero-activity CDRs excluded).",
    "campThresholdBasis": "Average Qualified PCs among CDRs with Campaigns activity this week (zero-activity CDRs excluded).",
    "note": "A CDR only qualifies for the ranking if their Qualified PCs meet or exceed both thresholds \u2014 Short Funnel AND Campaigns \u2014 regardless of how high their conversion rate is. This prevents small-sample outliers (e.g. 8 Qualified PCs / 8 ICs = 100%) from outranking sustained performance on a much larger base."
  },
  "summary": {
    "totalEvaluated": 60,
    "clubCount": 1,
    "eligibleCount": 2,
    "belowThresholdCount": 57
  },
  "cdrs": [
    {
      "cdr": "Rodrigo Cohen",
      "team": "The Booking Machines",
      "totalCallsOverall": 554,
      "qualifiedPCsOverall": 14,
      "icsOverall": 14,
      "overallPct": 100.00,
      "totalCallsSF": 71,
      "qualifiedPCsSF": 14,
      "icsSF": 14,
      "sfPct": 100.00,
      "totalCallsCamp": 483,
      "qualifiedPCsCamp": 0,
      "icsCamp": 0,
      "campPct": 0.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Iara Berdayes",
      "team": "Titans",
      "totalCallsOverall": 628,
      "qualifiedPCsOverall": 31,
      "icsOverall": 31,
      "overallPct": 100.00,
      "totalCallsSF": 75,
      "qualifiedPCsSF": 31,
      "icsSF": 31,
      "sfPct": 100.00,
      "totalCallsCamp": 553,
      "qualifiedPCsCamp": 0,
      "icsCamp": 0,
      "campPct": 0.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Milagros Cudeiro",
      "team": "Titans",
      "totalCallsOverall": 528,
      "qualifiedPCsOverall": 19,
      "icsOverall": 18,
      "overallPct": 94.74,
      "totalCallsSF": 171,
      "qualifiedPCsSF": 19,
      "icsSF": 18,
      "sfPct": 94.74,
      "totalCallsCamp": 357,
      "qualifiedPCsCamp": 0,
      "icsCamp": 0,
      "campPct": 0.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Monica Solon",
      "team": "Lightyear",
      "totalCallsOverall": 515,
      "qualifiedPCsOverall": 52,
      "icsOverall": 49,
      "overallPct": 94.23,
      "totalCallsSF": 515,
      "qualifiedPCsSF": 52,
      "icsSF": 49,
      "sfPct": 94.23,
      "totalCallsCamp": 0,
      "qualifiedPCsCamp": 0,
      "icsCamp": 0,
      "campPct": 0.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Martina Nasif",
      "team": "Titans",
      "totalCallsOverall": 576,
      "qualifiedPCsOverall": 40,
      "icsOverall": 37,
      "overallPct": 92.50,
      "totalCallsSF": 222,
      "qualifiedPCsSF": 39,
      "icsSF": 37,
      "sfPct": 94.87,
      "totalCallsCamp": 354,
      "qualifiedPCsCamp": 1,
      "icsCamp": 0,
      "campPct": 0.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Diego Brandan",
      "team": "The Booking Machines",
      "totalCallsOverall": 446,
      "qualifiedPCsOverall": 50,
      "icsOverall": 45,
      "overallPct": 90.00,
      "totalCallsSF": 328,
      "qualifiedPCsSF": 50,
      "icsSF": 45,
      "sfPct": 90.00,
      "totalCallsCamp": 118,
      "qualifiedPCsCamp": 0,
      "icsCamp": 0,
      "campPct": 0.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Marcio Oliveira",
      "team": "Lightyear",
      "totalCallsOverall": 424,
      "qualifiedPCsOverall": 52,
      "icsOverall": 46,
      "overallPct": 88.46,
      "totalCallsSF": 295,
      "qualifiedPCsSF": 52,
      "icsSF": 46,
      "sfPct": 88.46,
      "totalCallsCamp": 129,
      "qualifiedPCsCamp": 0,
      "icsCamp": 0,
      "campPct": 0.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Florencia Santos",
      "team": "Titans",
      "totalCallsOverall": 353,
      "qualifiedPCsOverall": 92,
      "icsOverall": 81,
      "overallPct": 88.04,
      "totalCallsSF": 297,
      "qualifiedPCsSF": 88,
      "icsSF": 80,
      "sfPct": 90.91,
      "totalCallsCamp": 56,
      "qualifiedPCsCamp": 4,
      "icsCamp": 1,
      "campPct": 25.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Valentina Franco",
      "team": "Lightyear",
      "totalCallsOverall": 366,
      "qualifiedPCsOverall": 21,
      "icsOverall": 18,
      "overallPct": 85.71,
      "totalCallsSF": 343,
      "qualifiedPCsSF": 20,
      "icsSF": 17,
      "sfPct": 85.00,
      "totalCallsCamp": 23,
      "qualifiedPCsCamp": 1,
      "icsCamp": 1,
      "campPct": 100.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Stephania Arcila Puerto",
      "team": "Lightyear",
      "totalCallsOverall": 565,
      "qualifiedPCsOverall": 30,
      "icsOverall": 25,
      "overallPct": 83.33,
      "totalCallsSF": 332,
      "qualifiedPCsSF": 30,
      "icsSF": 25,
      "sfPct": 83.33,
      "totalCallsCamp": 233,
      "qualifiedPCsCamp": 0,
      "icsCamp": 0,
      "campPct": 0.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Valentina Squillari",
      "team": "Titans",
      "totalCallsOverall": 495,
      "qualifiedPCsOverall": 64,
      "icsOverall": 53,
      "overallPct": 82.81,
      "totalCallsSF": 397,
      "qualifiedPCsSF": 56,
      "icsSF": 53,
      "sfPct": 94.64,
      "totalCallsCamp": 98,
      "qualifiedPCsCamp": 8,
      "icsCamp": 0,
      "campPct": 0.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Paula Brunati",
      "team": "Lightyear",
      "totalCallsOverall": 412,
      "qualifiedPCsOverall": 64,
      "icsOverall": 52,
      "overallPct": 81.25,
      "totalCallsSF": 399,
      "qualifiedPCsSF": 64,
      "icsSF": 52,
      "sfPct": 81.25,
      "totalCallsCamp": 13,
      "qualifiedPCsCamp": 0,
      "icsCamp": 0,
      "campPct": 0.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Alicia Romano",
      "team": "The Booking Machines",
      "totalCallsOverall": 506,
      "qualifiedPCsOverall": 56,
      "icsOverall": 45,
      "overallPct": 80.36,
      "totalCallsSF": 275,
      "qualifiedPCsSF": 54,
      "icsSF": 44,
      "sfPct": 81.48,
      "totalCallsCamp": 231,
      "qualifiedPCsCamp": 2,
      "icsCamp": 1,
      "campPct": 50.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Nicolas Soto",
      "team": "Titans",
      "totalCallsOverall": 752,
      "qualifiedPCsOverall": 94,
      "icsOverall": 72,
      "overallPct": 76.60,
      "totalCallsSF": 382,
      "qualifiedPCsSF": 76,
      "icsSF": 62,
      "sfPct": 81.58,
      "totalCallsCamp": 370,
      "qualifiedPCsCamp": 18,
      "icsCamp": 10,
      "campPct": 55.56,
      "status": "70club"
    },
    {
      "cdr": "Ianis Gavriz",
      "team": "Titans",
      "totalCallsOverall": 501,
      "qualifiedPCsOverall": 41,
      "icsOverall": 31,
      "overallPct": 75.61,
      "totalCallsSF": 173,
      "qualifiedPCsSF": 38,
      "icsSF": 29,
      "sfPct": 76.32,
      "totalCallsCamp": 328,
      "qualifiedPCsCamp": 3,
      "icsCamp": 2,
      "campPct": 66.67,
      "status": "below-threshold"
    },
    {
      "cdr": "Camila Aput",
      "team": "The Booking Machines",
      "totalCallsOverall": 579,
      "qualifiedPCsOverall": 20,
      "icsOverall": 15,
      "overallPct": 75.00,
      "totalCallsSF": 170,
      "qualifiedPCsSF": 20,
      "icsSF": 15,
      "sfPct": 75.00,
      "totalCallsCamp": 409,
      "qualifiedPCsCamp": 0,
      "icsCamp": 0,
      "campPct": 0.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Luis Ramirez",
      "team": "Lightyear",
      "totalCallsOverall": 456,
      "qualifiedPCsOverall": 8,
      "icsOverall": 6,
      "overallPct": 75.00,
      "totalCallsSF": 367,
      "qualifiedPCsSF": 8,
      "icsSF": 6,
      "sfPct": 75.00,
      "totalCallsCamp": 89,
      "qualifiedPCsCamp": 0,
      "icsCamp": 0,
      "campPct": 0.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Julieta Lorenzetti",
      "team": "Titans",
      "totalCallsOverall": 562,
      "qualifiedPCsOverall": 58,
      "icsOverall": 43,
      "overallPct": 74.14,
      "totalCallsSF": 336,
      "qualifiedPCsSF": 54,
      "icsSF": 42,
      "sfPct": 77.78,
      "totalCallsCamp": 226,
      "qualifiedPCsCamp": 4,
      "icsCamp": 1,
      "campPct": 25.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Tomas Vega",
      "team": "Lightyear",
      "totalCallsOverall": 513,
      "qualifiedPCsOverall": 48,
      "icsOverall": 35,
      "overallPct": 72.92,
      "totalCallsSF": 224,
      "qualifiedPCsSF": 47,
      "icsSF": 35,
      "sfPct": 74.47,
      "totalCallsCamp": 289,
      "qualifiedPCsCamp": 1,
      "icsCamp": 0,
      "campPct": 0.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Alan Castellano",
      "team": "The Booking Machines",
      "totalCallsOverall": 475,
      "qualifiedPCsOverall": 14,
      "icsOverall": 10,
      "overallPct": 71.43,
      "totalCallsSF": 137,
      "qualifiedPCsSF": 10,
      "icsSF": 10,
      "sfPct": 100.00,
      "totalCallsCamp": 338,
      "qualifiedPCsCamp": 4,
      "icsCamp": 0,
      "campPct": 0.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Pedro Moreno",
      "team": "The Booking Machines",
      "totalCallsOverall": 499,
      "qualifiedPCsOverall": 49,
      "icsOverall": 35,
      "overallPct": 71.43,
      "totalCallsSF": 421,
      "qualifiedPCsSF": 47,
      "icsSF": 34,
      "sfPct": 72.34,
      "totalCallsCamp": 78,
      "qualifiedPCsCamp": 2,
      "icsCamp": 1,
      "campPct": 50.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Juan Pablo Gutierrez",
      "team": "Titans",
      "totalCallsOverall": 545,
      "qualifiedPCsOverall": 70,
      "icsOverall": 50,
      "overallPct": 71.43,
      "totalCallsSF": 392,
      "qualifiedPCsSF": 64,
      "icsSF": 50,
      "sfPct": 78.13,
      "totalCallsCamp": 153,
      "qualifiedPCsCamp": 6,
      "icsCamp": 0,
      "campPct": 0.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Joao Campos",
      "team": "Lightyear",
      "totalCallsOverall": 616,
      "qualifiedPCsOverall": 41,
      "icsOverall": 29,
      "overallPct": 70.73,
      "totalCallsSF": 185,
      "qualifiedPCsSF": 33,
      "icsSF": 28,
      "sfPct": 84.85,
      "totalCallsCamp": 431,
      "qualifiedPCsCamp": 8,
      "icsCamp": 1,
      "campPct": 12.50,
      "status": "below-threshold"
    },
    {
      "cdr": "Stefania Ramundo",
      "team": "Lightyear",
      "totalCallsOverall": 528,
      "qualifiedPCsOverall": 45,
      "icsOverall": 31,
      "overallPct": 68.89,
      "totalCallsSF": 285,
      "qualifiedPCsSF": 36,
      "icsSF": 31,
      "sfPct": 86.11,
      "totalCallsCamp": 243,
      "qualifiedPCsCamp": 9,
      "icsCamp": 0,
      "campPct": 0.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Mariana Ricaurte",
      "team": "Lightyear",
      "totalCallsOverall": 513,
      "qualifiedPCsOverall": 22,
      "icsOverall": 15,
      "overallPct": 68.18,
      "totalCallsSF": 194,
      "qualifiedPCsSF": 22,
      "icsSF": 15,
      "sfPct": 68.18,
      "totalCallsCamp": 319,
      "qualifiedPCsCamp": 0,
      "icsCamp": 0,
      "campPct": 0.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Melissa Salas",
      "team": "Academia",
      "totalCallsOverall": 513,
      "qualifiedPCsOverall": 25,
      "icsOverall": 17,
      "overallPct": 68.00,
      "totalCallsSF": 152,
      "qualifiedPCsSF": 19,
      "icsSF": 15,
      "sfPct": 78.95,
      "totalCallsCamp": 361,
      "qualifiedPCsCamp": 6,
      "icsCamp": 2,
      "campPct": 33.33,
      "status": "below-threshold"
    },
    {
      "cdr": "Jesus Castillo",
      "team": "The Booking Machines",
      "totalCallsOverall": 395,
      "qualifiedPCsOverall": 18,
      "icsOverall": 12,
      "overallPct": 66.67,
      "totalCallsSF": 101,
      "qualifiedPCsSF": 15,
      "icsSF": 12,
      "sfPct": 80.00,
      "totalCallsCamp": 294,
      "qualifiedPCsCamp": 3,
      "icsCamp": 0,
      "campPct": 0.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Khomotso Mosena",
      "team": "Titans",
      "totalCallsOverall": 295,
      "qualifiedPCsOverall": 39,
      "icsOverall": 26,
      "overallPct": 66.67,
      "totalCallsSF": 263,
      "qualifiedPCsSF": 37,
      "icsSF": 26,
      "sfPct": 70.27,
      "totalCallsCamp": 32,
      "qualifiedPCsCamp": 2,
      "icsCamp": 0,
      "campPct": 0.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Laura Bracalenti",
      "team": "Lightyear",
      "totalCallsOverall": 490,
      "qualifiedPCsOverall": 63,
      "icsOverall": 40,
      "overallPct": 63.49,
      "totalCallsSF": 279,
      "qualifiedPCsSF": 58,
      "icsSF": 39,
      "sfPct": 67.24,
      "totalCallsCamp": 211,
      "qualifiedPCsCamp": 5,
      "icsCamp": 1,
      "campPct": 20.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Fernanda Fernandez",
      "team": "Lightyear",
      "totalCallsOverall": 695,
      "qualifiedPCsOverall": 43,
      "icsOverall": 27,
      "overallPct": 62.79,
      "totalCallsSF": 219,
      "qualifiedPCsSF": 41,
      "icsSF": 27,
      "sfPct": 65.85,
      "totalCallsCamp": 476,
      "qualifiedPCsCamp": 2,
      "icsCamp": 0,
      "campPct": 0.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Ayelen Mannucci",
      "team": "Lightyear",
      "totalCallsOverall": 431,
      "qualifiedPCsOverall": 51,
      "icsOverall": 32,
      "overallPct": 62.75,
      "totalCallsSF": 404,
      "qualifiedPCsSF": 50,
      "icsSF": 32,
      "sfPct": 64.00,
      "totalCallsCamp": 27,
      "qualifiedPCsCamp": 1,
      "icsCamp": 0,
      "campPct": 0.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Lucas DaSilva",
      "team": "The Booking Machines",
      "totalCallsOverall": 199,
      "qualifiedPCsOverall": 18,
      "icsOverall": 11,
      "overallPct": 61.11,
      "totalCallsSF": 172,
      "qualifiedPCsSF": 18,
      "icsSF": 11,
      "sfPct": 61.11,
      "totalCallsCamp": 27,
      "qualifiedPCsCamp": 0,
      "icsCamp": 0,
      "campPct": 0.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Loraine Castillo",
      "team": "Lightyear",
      "totalCallsOverall": 526,
      "qualifiedPCsOverall": 36,
      "icsOverall": 22,
      "overallPct": 61.11,
      "totalCallsSF": 323,
      "qualifiedPCsSF": 35,
      "icsSF": 22,
      "sfPct": 62.86,
      "totalCallsCamp": 203,
      "qualifiedPCsCamp": 1,
      "icsCamp": 0,
      "campPct": 0.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Marcos Villa",
      "team": "The Booking Machines",
      "totalCallsOverall": 505,
      "qualifiedPCsOverall": 40,
      "icsOverall": 24,
      "overallPct": 60.00,
      "totalCallsSF": 422,
      "qualifiedPCsSF": 37,
      "icsSF": 21,
      "sfPct": 56.76,
      "totalCallsCamp": 83,
      "qualifiedPCsCamp": 3,
      "icsCamp": 3,
      "campPct": 100.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Noraly Camargo",
      "team": "Titans",
      "totalCallsOverall": 377,
      "qualifiedPCsOverall": 40,
      "icsOverall": 24,
      "overallPct": 60.00,
      "totalCallsSF": 231,
      "qualifiedPCsSF": 35,
      "icsSF": 20,
      "sfPct": 57.14,
      "totalCallsCamp": 146,
      "qualifiedPCsCamp": 5,
      "icsCamp": 4,
      "campPct": 80.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Maria Camba",
      "team": "Lightyear",
      "totalCallsOverall": 555,
      "qualifiedPCsOverall": 29,
      "icsOverall": 17,
      "overallPct": 58.62,
      "totalCallsSF": 186,
      "qualifiedPCsSF": 21,
      "icsSF": 17,
      "sfPct": 80.95,
      "totalCallsCamp": 369,
      "qualifiedPCsCamp": 8,
      "icsCamp": 0,
      "campPct": 0.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Motunrayo Bamgbose",
      "team": "Titans",
      "totalCallsOverall": 558,
      "qualifiedPCsOverall": 59,
      "icsOverall": 32,
      "overallPct": 54.24,
      "totalCallsSF": 147,
      "qualifiedPCsSF": 33,
      "icsSF": 26,
      "sfPct": 78.79,
      "totalCallsCamp": 411,
      "qualifiedPCsCamp": 26,
      "icsCamp": 6,
      "campPct": 23.08,
      "status": "below-threshold"
    },
    {
      "cdr": "Alejandro Portillo",
      "team": "Titans",
      "totalCallsOverall": 385,
      "qualifiedPCsOverall": 60,
      "icsOverall": 32,
      "overallPct": 53.33,
      "totalCallsSF": 246,
      "qualifiedPCsSF": 41,
      "icsSF": 31,
      "sfPct": 75.61,
      "totalCallsCamp": 139,
      "qualifiedPCsCamp": 19,
      "icsCamp": 1,
      "campPct": 5.26,
      "status": "eligible"
    },
    {
      "cdr": "Alejandra Saa",
      "team": "Academia",
      "totalCallsOverall": 581,
      "qualifiedPCsOverall": 29,
      "icsOverall": 15,
      "overallPct": 51.72,
      "totalCallsSF": 219,
      "qualifiedPCsSF": 20,
      "icsSF": 13,
      "sfPct": 65.00,
      "totalCallsCamp": 362,
      "qualifiedPCsCamp": 9,
      "icsCamp": 2,
      "campPct": 22.22,
      "status": "below-threshold"
    },
    {
      "cdr": "Stefanny Navarro",
      "team": "The Booking Machines",
      "totalCallsOverall": 432,
      "qualifiedPCsOverall": 61,
      "icsOverall": 31,
      "overallPct": 50.82,
      "totalCallsSF": 395,
      "qualifiedPCsSF": 57,
      "icsSF": 31,
      "sfPct": 54.39,
      "totalCallsCamp": 37,
      "qualifiedPCsCamp": 4,
      "icsCamp": 0,
      "campPct": 0.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Agustin Mauvezin",
      "team": "Titans",
      "totalCallsOverall": 531,
      "qualifiedPCsOverall": 32,
      "icsOverall": 16,
      "overallPct": 50.00,
      "totalCallsSF": 253,
      "qualifiedPCsSF": 24,
      "icsSF": 15,
      "sfPct": 62.50,
      "totalCallsCamp": 278,
      "qualifiedPCsCamp": 8,
      "icsCamp": 1,
      "campPct": 12.50,
      "status": "below-threshold"
    },
    {
      "cdr": "Katheryn Parada",
      "team": "Lightyear",
      "totalCallsOverall": 156,
      "qualifiedPCsOverall": 25,
      "icsOverall": 11,
      "overallPct": 44.00,
      "totalCallsSF": 147,
      "qualifiedPCsSF": 19,
      "icsSF": 11,
      "sfPct": 57.89,
      "totalCallsCamp": 9,
      "qualifiedPCsCamp": 6,
      "icsCamp": 0,
      "campPct": 0.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Ailen Leiva",
      "team": "Academia",
      "totalCallsOverall": 178,
      "qualifiedPCsOverall": 16,
      "icsOverall": 7,
      "overallPct": 43.75,
      "totalCallsSF": 50,
      "qualifiedPCsSF": 9,
      "icsSF": 5,
      "sfPct": 55.56,
      "totalCallsCamp": 128,
      "qualifiedPCsCamp": 7,
      "icsCamp": 2,
      "campPct": 28.57,
      "status": "below-threshold"
    },
    {
      "cdr": "Ludmila Catalan",
      "team": "Titans",
      "totalCallsOverall": 712,
      "qualifiedPCsOverall": 36,
      "icsOverall": 15,
      "overallPct": 41.67,
      "totalCallsSF": 181,
      "qualifiedPCsSF": 25,
      "icsSF": 15,
      "sfPct": 60.00,
      "totalCallsCamp": 531,
      "qualifiedPCsCamp": 11,
      "icsCamp": 0,
      "campPct": 0.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Javier Garcia",
      "team": "The Booking Machines",
      "totalCallsOverall": 631,
      "qualifiedPCsOverall": 25,
      "icsOverall": 10,
      "overallPct": 40.00,
      "totalCallsSF": 111,
      "qualifiedPCsSF": 18,
      "icsSF": 9,
      "sfPct": 50.00,
      "totalCallsCamp": 520,
      "qualifiedPCsCamp": 7,
      "icsCamp": 1,
      "campPct": 14.29,
      "status": "below-threshold"
    },
    {
      "cdr": "Araceli Pinget",
      "team": "The Booking Machines",
      "totalCallsOverall": 545,
      "qualifiedPCsOverall": 71,
      "icsOverall": 26,
      "overallPct": 36.62,
      "totalCallsSF": 221,
      "qualifiedPCsSF": 43,
      "icsSF": 21,
      "sfPct": 48.84,
      "totalCallsCamp": 324,
      "qualifiedPCsCamp": 28,
      "icsCamp": 5,
      "campPct": 17.86,
      "status": "eligible"
    },
    {
      "cdr": "Cameron Moorcraft",
      "team": "Titans",
      "totalCallsOverall": 557,
      "qualifiedPCsOverall": 52,
      "icsOverall": 19,
      "overallPct": 36.54,
      "totalCallsSF": 248,
      "qualifiedPCsSF": 24,
      "icsSF": 17,
      "sfPct": 70.83,
      "totalCallsCamp": 309,
      "qualifiedPCsCamp": 28,
      "icsCamp": 2,
      "campPct": 7.14,
      "status": "below-threshold"
    },
    {
      "cdr": "Melissa Katemo",
      "team": "Titans",
      "totalCallsOverall": 475,
      "qualifiedPCsOverall": 72,
      "icsOverall": 26,
      "overallPct": 36.11,
      "totalCallsSF": 311,
      "qualifiedPCsSF": 62,
      "icsSF": 26,
      "sfPct": 41.94,
      "totalCallsCamp": 164,
      "qualifiedPCsCamp": 10,
      "icsCamp": 0,
      "campPct": 0.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Ximena Lopez",
      "team": "The Booking Machines",
      "totalCallsOverall": 900,
      "qualifiedPCsOverall": 31,
      "icsOverall": 11,
      "overallPct": 35.48,
      "totalCallsSF": 141,
      "qualifiedPCsSF": 17,
      "icsSF": 6,
      "sfPct": 35.29,
      "totalCallsCamp": 759,
      "qualifiedPCsCamp": 14,
      "icsCamp": 5,
      "campPct": 35.71,
      "status": "below-threshold"
    },
    {
      "cdr": "Natalia Colombo",
      "team": "Academia",
      "totalCallsOverall": 844,
      "qualifiedPCsOverall": 63,
      "icsOverall": 22,
      "overallPct": 34.92,
      "totalCallsSF": 108,
      "qualifiedPCsSF": 16,
      "icsSF": 15,
      "sfPct": 93.75,
      "totalCallsCamp": 736,
      "qualifiedPCsCamp": 47,
      "icsCamp": 7,
      "campPct": 14.89,
      "status": "below-threshold"
    },
    {
      "cdr": "Camila Abran",
      "team": "Academia",
      "totalCallsOverall": 732,
      "qualifiedPCsOverall": 38,
      "icsOverall": 13,
      "overallPct": 34.21,
      "totalCallsSF": 130,
      "qualifiedPCsSF": 12,
      "icsSF": 8,
      "sfPct": 66.67,
      "totalCallsCamp": 602,
      "qualifiedPCsCamp": 26,
      "icsCamp": 5,
      "campPct": 19.23,
      "status": "below-threshold"
    },
    {
      "cdr": "George Tzaferi",
      "team": "Lightyear",
      "totalCallsOverall": 630,
      "qualifiedPCsOverall": 52,
      "icsOverall": 17,
      "overallPct": 32.69,
      "totalCallsSF": 167,
      "qualifiedPCsSF": 23,
      "icsSF": 12,
      "sfPct": 52.17,
      "totalCallsCamp": 463,
      "qualifiedPCsCamp": 29,
      "icsCamp": 5,
      "campPct": 17.24,
      "status": "below-threshold"
    },
    {
      "cdr": "Lihue Alvarez",
      "team": "Academia",
      "totalCallsOverall": 670,
      "qualifiedPCsOverall": 35,
      "icsOverall": 10,
      "overallPct": 28.57,
      "totalCallsSF": 56,
      "qualifiedPCsSF": 14,
      "icsSF": 8,
      "sfPct": 57.14,
      "totalCallsCamp": 614,
      "qualifiedPCsCamp": 21,
      "icsCamp": 2,
      "campPct": 9.52,
      "status": "below-threshold"
    },
    {
      "cdr": "Renee Castillo",
      "team": "The Booking Machines",
      "totalCallsOverall": 254,
      "qualifiedPCsOverall": 25,
      "icsOverall": 7,
      "overallPct": 28.00,
      "totalCallsSF": 108,
      "qualifiedPCsSF": 19,
      "icsSF": 7,
      "sfPct": 36.84,
      "totalCallsCamp": 146,
      "qualifiedPCsCamp": 6,
      "icsCamp": 0,
      "campPct": 0.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Oriana Tuttobene",
      "team": "Lightyear",
      "totalCallsOverall": 1166,
      "qualifiedPCsOverall": 33,
      "icsOverall": 9,
      "overallPct": 27.27,
      "totalCallsSF": 240,
      "qualifiedPCsSF": 10,
      "icsSF": 8,
      "sfPct": 80.00,
      "totalCallsCamp": 926,
      "qualifiedPCsCamp": 23,
      "icsCamp": 1,
      "campPct": 4.35,
      "status": "below-threshold"
    },
    {
      "cdr": "Victoria Antunes Bueno",
      "team": "Titans",
      "totalCallsOverall": 645,
      "qualifiedPCsOverall": 34,
      "icsOverall": 9,
      "overallPct": 26.47,
      "totalCallsSF": 107,
      "qualifiedPCsSF": 7,
      "icsSF": 4,
      "sfPct": 57.14,
      "totalCallsCamp": 538,
      "qualifiedPCsCamp": 27,
      "icsCamp": 5,
      "campPct": 18.52,
      "status": "below-threshold"
    },
    {
      "cdr": "Kevin Perez",
      "team": "The Booking Machines",
      "totalCallsOverall": 791,
      "qualifiedPCsOverall": 35,
      "icsOverall": 9,
      "overallPct": 25.71,
      "totalCallsSF": 133,
      "qualifiedPCsSF": 16,
      "icsSF": 8,
      "sfPct": 50.00,
      "totalCallsCamp": 658,
      "qualifiedPCsCamp": 19,
      "icsCamp": 1,
      "campPct": 5.26,
      "status": "below-threshold"
    },
    {
      "cdr": "Juan Milano",
      "team": "Academia",
      "totalCallsOverall": 795,
      "qualifiedPCsOverall": 63,
      "icsOverall": 8,
      "overallPct": 12.70,
      "totalCallsSF": 105,
      "qualifiedPCsSF": 19,
      "icsSF": 7,
      "sfPct": 36.84,
      "totalCallsCamp": 690,
      "qualifiedPCsCamp": 44,
      "icsCamp": 1,
      "campPct": 2.27,
      "status": "below-threshold"
    },
    {
      "cdr": "Lionel Katemo",
      "team": "Titans",
      "totalCallsOverall": 4,
      "qualifiedPCsOverall": 0,
      "icsOverall": 0,
      "overallPct": 0.00,
      "totalCallsSF": 4,
      "qualifiedPCsSF": 0,
      "icsSF": 0,
      "sfPct": 0.00,
      "totalCallsCamp": 0,
      "qualifiedPCsCamp": 0,
      "icsCamp": 0,
      "campPct": 0.00,
      "status": "below-threshold"
    },
    {
      "cdr": "Aldemara Barbosa",
      "team": "Lightyear",
      "totalCallsOverall": 5,
      "qualifiedPCsOverall": 0,
      "icsOverall": 0,
      "overallPct": 0.00,
      "totalCallsSF": 5,
      "qualifiedPCsSF": 0,
      "icsSF": 0,
      "sfPct": 0.00,
      "totalCallsCamp": 0,
      "qualifiedPCsCamp": 0,
      "icsCamp": 0,
      "campPct": 0.00,
      "status": "below-threshold"
    }
  ],
  "observations": [
    "Only Nicolas Soto (Titans) cleared both volume thresholds and reached 70%+ overall this week (76.6%) \u2014 the sole member of The 70% Club.",
    "Alejandro Portillo and Araceli Pinget met the volume bar in both funnels but stayed under 70% overall (53.33% and 36.62% respectively), landing as Eligible rather than in the Club.",
    "Several CDRs posted very high overall percentages \u2014 Rodrigo Cohen and Iara Berdayes both at 100% \u2014 but had zero Qualified PCs in Campaigns this week, exactly the kind of small or one-sided sample the volume filter is designed to screen out.",
    "This week's thresholds (33.1 Qualified PCs in SF / 11.4 in Campaigns) are higher than the reference week used to design the methodology (26.1 / 8.5), reflecting the decision to exclude zero-activity CDRs when averaging."
  ]
}
];

export function getConversionTrackerReportById(id: string): ConversionTrackerData | undefined {
  return mockConversionTrackerReports.find((r) => r.id === id);
}
