import { ConversionTrackerData } from "./types";

export const mockConversionTrackerReports: ConversionTrackerData[] = [
{
  "id": "conversion-tracker-0914-0920",
  "metadata": {
    "reportType": "CDR Conversion Tracker",
    "cadence": "Weekly",
    "periodLabel": "09/14 \u2013 09/20"
  },
  "methodology": {
    "sfThreshold": 33.1,
    "campThreshold": 11.4,
    "sfThresholdBasis": "Average Qualified PCs among CDRs with Short Funnel activity this week (zero-activity CDRs excluded).",
    "campThresholdBasis": "Average Qualified PCs among CDRs with Campaigns activity this week (zero-activity CDRs excluded).",
    "note": "A CDR only qualifies for the ranking if their Qualified PCs meet or exceed both thresholds \u2014 Short Funnel AND Campaigns \u2014 regardless of how high their conversion rate is. This prevents small-sample outliers (e.g. 8 Qualified PCs / 8 ICs = 100%) from outranking sustained performance on a much larger base."
  },
  "summary": {
    "totalEvaluated": 60,
    "clubCount": 1,
    "eligibleCount": 2,
    "belowThresholdCount": 57
  },
  "cdrs": [
    {
      "cdr": "Rodrigo Cohen",
      "team": "Lightyear",
      "qualifiedPCsOverall": 14,
      "icsOverall": 14,
      "overallPct": 100.0,
      "qualifiedPCsSF": 14,
      "icsSF": 14,
      "sfPct": 100.0,
      "qualifiedPCsCamp": 0,
      "icsCamp": 0,
      "campPct": 0.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Iara Berdayes",
      "team": "Titans",
      "qualifiedPCsOverall": 31,
      "icsOverall": 31,
      "overallPct": 100.0,
      "qualifiedPCsSF": 31,
      "icsSF": 31,
      "sfPct": 100.0,
      "qualifiedPCsCamp": 0,
      "icsCamp": 0,
      "campPct": 0.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Milagros Cudeiro",
      "team": "Titans",
      "qualifiedPCsOverall": 19,
      "icsOverall": 18,
      "overallPct": 94.74,
      "qualifiedPCsSF": 19,
      "icsSF": 18,
      "sfPct": 94.74,
      "qualifiedPCsCamp": 0,
      "icsCamp": 0,
      "campPct": 0.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Monica Solon",
      "team": "The Booking Machines",
      "qualifiedPCsOverall": 52,
      "icsOverall": 49,
      "overallPct": 94.23,
      "qualifiedPCsSF": 52,
      "icsSF": 49,
      "sfPct": 94.23,
      "qualifiedPCsCamp": 0,
      "icsCamp": 0,
      "campPct": 0.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Martina Nasif",
      "team": "Titans",
      "qualifiedPCsOverall": 40,
      "icsOverall": 37,
      "overallPct": 92.5,
      "qualifiedPCsSF": 39,
      "icsSF": 37,
      "sfPct": 94.87,
      "qualifiedPCsCamp": 1,
      "icsCamp": 0,
      "campPct": 0.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Diego Brandan",
      "team": "Lightyear",
      "qualifiedPCsOverall": 50,
      "icsOverall": 45,
      "overallPct": 90.0,
      "qualifiedPCsSF": 50,
      "icsSF": 45,
      "sfPct": 90.0,
      "qualifiedPCsCamp": 0,
      "icsCamp": 0,
      "campPct": 0.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Marcio Oliveira",
      "team": "The Booking Machines",
      "qualifiedPCsOverall": 52,
      "icsOverall": 46,
      "overallPct": 88.46,
      "qualifiedPCsSF": 52,
      "icsSF": 46,
      "sfPct": 88.46,
      "qualifiedPCsCamp": 0,
      "icsCamp": 0,
      "campPct": 0.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Florencia Santos",
      "team": "Titans",
      "qualifiedPCsOverall": 92,
      "icsOverall": 81,
      "overallPct": 88.04,
      "qualifiedPCsSF": 88,
      "icsSF": 80,
      "sfPct": 90.91,
      "qualifiedPCsCamp": 4,
      "icsCamp": 1,
      "campPct": 25.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Valentina Franco",
      "team": "The Booking Machines",
      "qualifiedPCsOverall": 21,
      "icsOverall": 18,
      "overallPct": 85.71,
      "qualifiedPCsSF": 20,
      "icsSF": 17,
      "sfPct": 85.0,
      "qualifiedPCsCamp": 1,
      "icsCamp": 1,
      "campPct": 100.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Stephania Arcila Puerto",
      "team": "The Booking Machines",
      "qualifiedPCsOverall": 30,
      "icsOverall": 25,
      "overallPct": 83.33,
      "qualifiedPCsSF": 30,
      "icsSF": 25,
      "sfPct": 83.33,
      "qualifiedPCsCamp": 0,
      "icsCamp": 0,
      "campPct": 0.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Valentina Squillari",
      "team": "Titans",
      "qualifiedPCsOverall": 64,
      "icsOverall": 53,
      "overallPct": 82.81,
      "qualifiedPCsSF": 56,
      "icsSF": 53,
      "sfPct": 94.64,
      "qualifiedPCsCamp": 8,
      "icsCamp": 0,
      "campPct": 0.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Paula Brunati",
      "team": "The Booking Machines",
      "qualifiedPCsOverall": 64,
      "icsOverall": 52,
      "overallPct": 81.25,
      "qualifiedPCsSF": 64,
      "icsSF": 52,
      "sfPct": 81.25,
      "qualifiedPCsCamp": 0,
      "icsCamp": 0,
      "campPct": 0.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Alicia Romano",
      "team": "Lightyear",
      "qualifiedPCsOverall": 56,
      "icsOverall": 45,
      "overallPct": 80.36,
      "qualifiedPCsSF": 54,
      "icsSF": 44,
      "sfPct": 81.48,
      "qualifiedPCsCamp": 2,
      "icsCamp": 1,
      "campPct": 50.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Nicolas Soto",
      "team": "Titans",
      "qualifiedPCsOverall": 94,
      "icsOverall": 72,
      "overallPct": 76.6,
      "qualifiedPCsSF": 76,
      "icsSF": 62,
      "sfPct": 81.58,
      "qualifiedPCsCamp": 18,
      "icsCamp": 10,
      "campPct": 55.56,
      "status": "70club"
    },
    {
      "cdr": "Ianis Gavriz",
      "team": "Titans",
      "qualifiedPCsOverall": 41,
      "icsOverall": 31,
      "overallPct": 75.61,
      "qualifiedPCsSF": 38,
      "icsSF": 29,
      "sfPct": 76.32,
      "qualifiedPCsCamp": 3,
      "icsCamp": 2,
      "campPct": 66.67,
      "status": "below-threshold"
    },
    {
      "cdr": "Camila Aput",
      "team": "Lightyear",
      "qualifiedPCsOverall": 20,
      "icsOverall": 15,
      "overallPct": 75.0,
      "qualifiedPCsSF": 20,
      "icsSF": 15,
      "sfPct": 75.0,
      "qualifiedPCsCamp": 0,
      "icsCamp": 0,
      "campPct": 0.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Luis Ramirez",
      "team": "The Booking Machines",
      "qualifiedPCsOverall": 8,
      "icsOverall": 6,
      "overallPct": 75.0,
      "qualifiedPCsSF": 8,
      "icsSF": 6,
      "sfPct": 75.0,
      "qualifiedPCsCamp": 0,
      "icsCamp": 0,
      "campPct": 0.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Julieta Lorenzetti",
      "team": "Titans",
      "qualifiedPCsOverall": 58,
      "icsOverall": 43,
      "overallPct": 74.14,
      "qualifiedPCsSF": 54,
      "icsSF": 42,
      "sfPct": 77.78,
      "qualifiedPCsCamp": 4,
      "icsCamp": 1,
      "campPct": 25.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Tomas Vega",
      "team": "The Booking Machines",
      "qualifiedPCsOverall": 48,
      "icsOverall": 35,
      "overallPct": 72.92,
      "qualifiedPCsSF": 47,
      "icsSF": 35,
      "sfPct": 74.47,
      "qualifiedPCsCamp": 1,
      "icsCamp": 0,
      "campPct": 0.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Alan Castellano",
      "team": "Lightyear",
      "qualifiedPCsOverall": 14,
      "icsOverall": 10,
      "overallPct": 71.43,
      "qualifiedPCsSF": 10,
      "icsSF": 10,
      "sfPct": 100.0,
      "qualifiedPCsCamp": 4,
      "icsCamp": 0,
      "campPct": 0.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Pedro Moreno",
      "team": "Lightyear",
      "qualifiedPCsOverall": 49,
      "icsOverall": 35,
      "overallPct": 71.43,
      "qualifiedPCsSF": 47,
      "icsSF": 34,
      "sfPct": 72.34,
      "qualifiedPCsCamp": 2,
      "icsCamp": 1,
      "campPct": 50.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Juan Pablo Gutierrez",
      "team": "Titans",
      "qualifiedPCsOverall": 70,
      "icsOverall": 50,
      "overallPct": 71.43,
      "qualifiedPCsSF": 64,
      "icsSF": 50,
      "sfPct": 78.12,
      "qualifiedPCsCamp": 6,
      "icsCamp": 0,
      "campPct": 0.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Joao Miguel Campos",
      "team": "The Booking Machines",
      "qualifiedPCsOverall": 41,
      "icsOverall": 29,
      "overallPct": 70.73,
      "qualifiedPCsSF": 33,
      "icsSF": 28,
      "sfPct": 84.85,
      "qualifiedPCsCamp": 8,
      "icsCamp": 1,
      "campPct": 12.5,
      "status": "below-threshold"
    },
    {
      "cdr": "Stefania Ramundo",
      "team": "The Booking Machines",
      "qualifiedPCsOverall": 45,
      "icsOverall": 31,
      "overallPct": 68.89,
      "qualifiedPCsSF": 36,
      "icsSF": 31,
      "sfPct": 86.11,
      "qualifiedPCsCamp": 9,
      "icsCamp": 0,
      "campPct": 0.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Mariana Ricaurte",
      "team": "The Booking Machines",
      "qualifiedPCsOverall": 22,
      "icsOverall": 15,
      "overallPct": 68.18,
      "qualifiedPCsSF": 22,
      "icsSF": 15,
      "sfPct": 68.18,
      "qualifiedPCsCamp": 0,
      "icsCamp": 0,
      "campPct": 0.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Melissa Salas",
      "team": "Academia",
      "qualifiedPCsOverall": 25,
      "icsOverall": 17,
      "overallPct": 68.0,
      "qualifiedPCsSF": 19,
      "icsSF": 15,
      "sfPct": 78.95,
      "qualifiedPCsCamp": 6,
      "icsCamp": 2,
      "campPct": 33.33,
      "status": "below-threshold"
    },
    {
      "cdr": "Jesus Castillo",
      "team": "Lightyear",
      "qualifiedPCsOverall": 18,
      "icsOverall": 12,
      "overallPct": 66.67,
      "qualifiedPCsSF": 15,
      "icsSF": 12,
      "sfPct": 80.0,
      "qualifiedPCsCamp": 3,
      "icsCamp": 0,
      "campPct": 0.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Khomotso Mosena",
      "team": "Titans",
      "qualifiedPCsOverall": 39,
      "icsOverall": 26,
      "overallPct": 66.67,
      "qualifiedPCsSF": 37,
      "icsSF": 26,
      "sfPct": 70.27,
      "qualifiedPCsCamp": 2,
      "icsCamp": 0,
      "campPct": 0.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Laura Bracalenti",
      "team": "The Booking Machines",
      "qualifiedPCsOverall": 63,
      "icsOverall": 40,
      "overallPct": 63.49,
      "qualifiedPCsSF": 58,
      "icsSF": 39,
      "sfPct": 67.24,
      "qualifiedPCsCamp": 5,
      "icsCamp": 1,
      "campPct": 20.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Fernanda Fernandez",
      "team": "The Booking Machines",
      "qualifiedPCsOverall": 43,
      "icsOverall": 27,
      "overallPct": 62.79,
      "qualifiedPCsSF": 41,
      "icsSF": 27,
      "sfPct": 65.85,
      "qualifiedPCsCamp": 2,
      "icsCamp": 0,
      "campPct": 0.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Ayelen Mannucci",
      "team": "The Booking Machines",
      "qualifiedPCsOverall": 51,
      "icsOverall": 32,
      "overallPct": 62.75,
      "qualifiedPCsSF": 50,
      "icsSF": 32,
      "sfPct": 64.0,
      "qualifiedPCsCamp": 1,
      "icsCamp": 0,
      "campPct": 0.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Lucas DaSilva",
      "team": "Lightyear",
      "qualifiedPCsOverall": 18,
      "icsOverall": 11,
      "overallPct": 61.11,
      "qualifiedPCsSF": 18,
      "icsSF": 11,
      "sfPct": 61.11,
      "qualifiedPCsCamp": 0,
      "icsCamp": 0,
      "campPct": 0.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Loraine Castillo",
      "team": "The Booking Machines",
      "qualifiedPCsOverall": 36,
      "icsOverall": 22,
      "overallPct": 61.11,
      "qualifiedPCsSF": 35,
      "icsSF": 22,
      "sfPct": 62.86,
      "qualifiedPCsCamp": 1,
      "icsCamp": 0,
      "campPct": 0.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Marcos Villa",
      "team": "Lightyear",
      "qualifiedPCsOverall": 40,
      "icsOverall": 24,
      "overallPct": 60.0,
      "qualifiedPCsSF": 37,
      "icsSF": 21,
      "sfPct": 56.76,
      "qualifiedPCsCamp": 3,
      "icsCamp": 3,
      "campPct": 100.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Noraly Camargo",
      "team": "Titans",
      "qualifiedPCsOverall": 40,
      "icsOverall": 24,
      "overallPct": 60.0,
      "qualifiedPCsSF": 35,
      "icsSF": 20,
      "sfPct": 57.14,
      "qualifiedPCsCamp": 5,
      "icsCamp": 4,
      "campPct": 80.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Maria Camba",
      "team": "The Booking Machines",
      "qualifiedPCsOverall": 29,
      "icsOverall": 17,
      "overallPct": 58.62,
      "qualifiedPCsSF": 21,
      "icsSF": 17,
      "sfPct": 80.95,
      "qualifiedPCsCamp": 8,
      "icsCamp": 0,
      "campPct": 0.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Motunrayo Bamgbose",
      "team": "Titans",
      "qualifiedPCsOverall": 59,
      "icsOverall": 32,
      "overallPct": 54.24,
      "qualifiedPCsSF": 33,
      "icsSF": 26,
      "sfPct": 78.79,
      "qualifiedPCsCamp": 26,
      "icsCamp": 6,
      "campPct": 23.08,
      "status": "below-threshold"
    },
    {
      "cdr": "Alejandro Portillo",
      "team": "Titans",
      "qualifiedPCsOverall": 60,
      "icsOverall": 32,
      "overallPct": 53.33,
      "qualifiedPCsSF": 41,
      "icsSF": 31,
      "sfPct": 75.61,
      "qualifiedPCsCamp": 19,
      "icsCamp": 1,
      "campPct": 5.26,
      "status": "eligible"
    },
    {
      "cdr": "Alejandra Saa",
      "team": "Academia",
      "qualifiedPCsOverall": 29,
      "icsOverall": 15,
      "overallPct": 51.72,
      "qualifiedPCsSF": 20,
      "icsSF": 13,
      "sfPct": 65.0,
      "qualifiedPCsCamp": 9,
      "icsCamp": 2,
      "campPct": 22.22,
      "status": "below-threshold"
    },
    {
      "cdr": "Stefanny Navarro",
      "team": "Lightyear",
      "qualifiedPCsOverall": 61,
      "icsOverall": 31,
      "overallPct": 50.82,
      "qualifiedPCsSF": 57,
      "icsSF": 31,
      "sfPct": 54.39,
      "qualifiedPCsCamp": 4,
      "icsCamp": 0,
      "campPct": 0.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Agustin Mauvezin",
      "team": "Titans",
      "qualifiedPCsOverall": 32,
      "icsOverall": 16,
      "overallPct": 50.0,
      "qualifiedPCsSF": 24,
      "icsSF": 15,
      "sfPct": 62.5,
      "qualifiedPCsCamp": 8,
      "icsCamp": 1,
      "campPct": 12.5,
      "status": "below-threshold"
    },
    {
      "cdr": "Katheryn Parada",
      "team": "The Booking Machines",
      "qualifiedPCsOverall": 25,
      "icsOverall": 11,
      "overallPct": 44.0,
      "qualifiedPCsSF": 19,
      "icsSF": 11,
      "sfPct": 57.89,
      "qualifiedPCsCamp": 6,
      "icsCamp": 0,
      "campPct": 0.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Ailen Leiva",
      "team": "Academia",
      "qualifiedPCsOverall": 16,
      "icsOverall": 7,
      "overallPct": 43.75,
      "qualifiedPCsSF": 9,
      "icsSF": 5,
      "sfPct": 55.56,
      "qualifiedPCsCamp": 7,
      "icsCamp": 2,
      "campPct": 28.57,
      "status": "below-threshold"
    },
    {
      "cdr": "Ludmila Catalan",
      "team": "Titans",
      "qualifiedPCsOverall": 36,
      "icsOverall": 15,
      "overallPct": 41.67,
      "qualifiedPCsSF": 25,
      "icsSF": 15,
      "sfPct": 60.0,
      "qualifiedPCsCamp": 11,
      "icsCamp": 0,
      "campPct": 0.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Javier Garcia",
      "team": "Lightyear",
      "qualifiedPCsOverall": 25,
      "icsOverall": 10,
      "overallPct": 40.0,
      "qualifiedPCsSF": 18,
      "icsSF": 9,
      "sfPct": 50.0,
      "qualifiedPCsCamp": 7,
      "icsCamp": 1,
      "campPct": 14.29,
      "status": "below-threshold"
    },
    {
      "cdr": "Araceli Pinget",
      "team": "Lightyear",
      "qualifiedPCsOverall": 71,
      "icsOverall": 26,
      "overallPct": 36.62,
      "qualifiedPCsSF": 43,
      "icsSF": 21,
      "sfPct": 48.84,
      "qualifiedPCsCamp": 28,
      "icsCamp": 5,
      "campPct": 17.86,
      "status": "eligible"
    },
    {
      "cdr": "Cameron Moorcraft",
      "team": "Titans",
      "qualifiedPCsOverall": 52,
      "icsOverall": 19,
      "overallPct": 36.54,
      "qualifiedPCsSF": 24,
      "icsSF": 17,
      "sfPct": 70.83,
      "qualifiedPCsCamp": 28,
      "icsCamp": 2,
      "campPct": 7.14,
      "status": "below-threshold"
    },
    {
      "cdr": "Melissa Katemo",
      "team": "Titans",
      "qualifiedPCsOverall": 72,
      "icsOverall": 26,
      "overallPct": 36.11,
      "qualifiedPCsSF": 62,
      "icsSF": 26,
      "sfPct": 41.94,
      "qualifiedPCsCamp": 10,
      "icsCamp": 0,
      "campPct": 0.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Ximena Lopez",
      "team": "Lightyear",
      "qualifiedPCsOverall": 31,
      "icsOverall": 11,
      "overallPct": 35.48,
      "qualifiedPCsSF": 17,
      "icsSF": 6,
      "sfPct": 35.29,
      "qualifiedPCsCamp": 14,
      "icsCamp": 5,
      "campPct": 35.71,
      "status": "below-threshold"
    },
    {
      "cdr": "Natalia Colombo",
      "team": "Academia",
      "qualifiedPCsOverall": 63,
      "icsOverall": 22,
      "overallPct": 34.92,
      "qualifiedPCsSF": 16,
      "icsSF": 15,
      "sfPct": 93.75,
      "qualifiedPCsCamp": 47,
      "icsCamp": 7,
      "campPct": 14.89,
      "status": "below-threshold"
    },
    {
      "cdr": "Camila Abran",
      "team": "Academia",
      "qualifiedPCsOverall": 38,
      "icsOverall": 13,
      "overallPct": 34.21,
      "qualifiedPCsSF": 12,
      "icsSF": 8,
      "sfPct": 66.67,
      "qualifiedPCsCamp": 26,
      "icsCamp": 5,
      "campPct": 19.23,
      "status": "below-threshold"
    },
    {
      "cdr": "George Tzaferi",
      "team": "The Booking Machines",
      "qualifiedPCsOverall": 52,
      "icsOverall": 17,
      "overallPct": 32.69,
      "qualifiedPCsSF": 23,
      "icsSF": 12,
      "sfPct": 52.17,
      "qualifiedPCsCamp": 29,
      "icsCamp": 5,
      "campPct": 17.24,
      "status": "below-threshold"
    },
    {
      "cdr": "Lihue Alvarez",
      "team": "Academia",
      "qualifiedPCsOverall": 35,
      "icsOverall": 10,
      "overallPct": 28.57,
      "qualifiedPCsSF": 14,
      "icsSF": 8,
      "sfPct": 57.14,
      "qualifiedPCsCamp": 21,
      "icsCamp": 2,
      "campPct": 9.52,
      "status": "below-threshold"
    },
    {
      "cdr": "Renee Castillo",
      "team": "Lightyear",
      "qualifiedPCsOverall": 25,
      "icsOverall": 7,
      "overallPct": 28.0,
      "qualifiedPCsSF": 19,
      "icsSF": 7,
      "sfPct": 36.84,
      "qualifiedPCsCamp": 6,
      "icsCamp": 0,
      "campPct": 0.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Oriana Tuttobene",
      "team": "The Booking Machines",
      "qualifiedPCsOverall": 33,
      "icsOverall": 9,
      "overallPct": 27.27,
      "qualifiedPCsSF": 10,
      "icsSF": 8,
      "sfPct": 80.0,
      "qualifiedPCsCamp": 23,
      "icsCamp": 1,
      "campPct": 4.35,
      "status": "below-threshold"
    },
    {
      "cdr": "Victoria Antunes Bueno",
      "team": "Titans",
      "qualifiedPCsOverall": 34,
      "icsOverall": 9,
      "overallPct": 26.47,
      "qualifiedPCsSF": 7,
      "icsSF": 4,
      "sfPct": 57.14,
      "qualifiedPCsCamp": 27,
      "icsCamp": 5,
      "campPct": 18.52,
      "status": "below-threshold"
    },
    {
      "cdr": "Kevin Perez",
      "team": "Lightyear",
      "qualifiedPCsOverall": 35,
      "icsOverall": 9,
      "overallPct": 25.71,
      "qualifiedPCsSF": 16,
      "icsSF": 8,
      "sfPct": 50.0,
      "qualifiedPCsCamp": 19,
      "icsCamp": 1,
      "campPct": 5.26,
      "status": "below-threshold"
    },
    {
      "cdr": "Juan Milano",
      "team": "Academia",
      "qualifiedPCsOverall": 63,
      "icsOverall": 8,
      "overallPct": 12.7,
      "qualifiedPCsSF": 19,
      "icsSF": 7,
      "sfPct": 36.84,
      "qualifiedPCsCamp": 44,
      "icsCamp": 1,
      "campPct": 2.27,
      "status": "below-threshold"
    },
    {
      "cdr": "Lionel Katemo",
      "team": "Titans",
      "qualifiedPCsOverall": 0,
      "icsOverall": 0,
      "overallPct": 0.0,
      "qualifiedPCsSF": 0,
      "icsSF": 0,
      "sfPct": 0.0,
      "qualifiedPCsCamp": 0,
      "icsCamp": 0,
      "campPct": 0.0,
      "status": "below-threshold"
    },
    {
      "cdr": "Aldemara Barbosa",
      "team": "The Booking Machines",
      "qualifiedPCsOverall": 0,
      "icsOverall": 0,
      "overallPct": 0.0,
      "qualifiedPCsSF": 0,
      "icsSF": 0,
      "sfPct": 0.0,
      "qualifiedPCsCamp": 0,
      "icsCamp": 0,
      "campPct": 0.0,
      "status": "below-threshold"
    }
  ],
  "observations": [
    "Only Nicolas Soto (Titans) cleared both volume thresholds and reached 70%+ overall this week (76.6%) \u2014 the sole member of The 70% Club.",
    "Alejandro Portillo and Araceli Pinget met the volume bar in both funnels but stayed under 70% overall (53.33% and 36.62% respectively), landing as Eligible rather than in the Club.",
    "Several CDRs posted very high overall percentages \u2014 Rodrigo Cohen and Iara Berdayes both at 100% \u2014 but had zero Qualified PCs in Campaigns this week, exactly the kind of small or one-sided sample the volume filter is designed to screen out.",
    "This week's thresholds (33.1 Qualified PCs in SF / 11.4 in Campaigns) are higher than the reference week used to design the methodology (26.1 / 8.5), reflecting the decision to exclude zero-activity CDRs when averaging."
  ]
}
];

export function getConversionTrackerReportById(id: string): ConversionTrackerData | undefined {
  return mockConversionTrackerReports.find((r) => r.id === id);
}
